### ISSUE TITLE
White bar/line at the bottom of closed issues

### ISSUE THREAD

**Issue by brian6932** [Ziyadsk/GithubDarkStyle#4]
Screenshot: https://imgur.com/MscuuQy
Source: https://github.com/Ziyadsk/GithubDarkStyle/issues/3

**Comment by Ziyadsk** [comment]
This has been fixed ! thanks again @brian6932

**Comment by brian6932** [comment]
👍

**Comment by brian6932** [comment]
I reinstalled 1.0.3 and the issue still persists https://imgur.com/a/VB79PiZ

**Comment by Ziyadsk** [comment]
don't reinstall 1.0.3 update to 1.0.4

**Comment by brian6932** [comment]
for some reason stylus didn't show an update, but when deleting and reinstalling the script 1.0.4 showed up
